project:
  type: book

book:
  title: "The Tufts Research Data Warehouse (TRDW)"
  author: "Tufts Clinical and Translational Science Institute (Tufts CTSI)"
  date: 2023-09-23
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    output-file: trdw-handbook
    output-ext: pdf
